# Default values for blockscout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/netwarps/blockscout@sha256
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "becd3e39360a6f58b1effa1b2b7d772795f8acdb96cd4c3b1455a02d9d749387"


command: ["/bin/sh"]
args: ["-c", "bin/blockscout start"]

initContainer:
  command: ["/bin/sh"]
  args: ["-c", "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\""]

env:
  - name: ETHEREUM_JSONRPC_VARIANT
    value: "geth"
  - name: COIN
    value: "SC"
  - name: COIN_NAME
    value: "SC"
  - name: ETHEREUM_JSONRPC_HTTP_URL
    value: "http://127.0.0.1:8545"
  - name: ETHEREUM_JSONRPC_WS_URL
    value: "ws://127.0.0.1:8546"
  - name: INDEXER_MEMORY_LIMIT
    value: "1gb"
  - name: BLOCK_TRANSFORMER
    value: "clique"
  - name: NETWORK
    value: "Solar Chain"
  - name: SUBNETWORK
    value: "Solar Chain Testnet"
  - name: LOGO
    value: "/images/chain-wallet.png"
  - name: LOGO_FOOTER
    value: "/images/chain-wallet.png"
  - name: BLOCKSCOUT_VERSION
    value: "c3f2caf8ed0bfb5e0992520b9e270f699c9a404e"
  - name: RELEASE_LINK
    value: "https://github.com/paradeum-team/blockscout/releases/tag/${BLOCKSCOUT_VERSION}"
  - name: DISABLE_EXCHANGE_RATES
    value: "true"
  - name: DISABLE_KNOWN_TOKENS
    value: "true"
  - name: SHOW_ADDRESS_MARKETCAP_PERCENTAGE
    value: "false"
  - name: SHOW_PRICE_CHART
    value: "false"
  - name: DISABLE_BRIDGE_MARKET_CAP_UPDATER
    value: "true"
  - name: SHOW_TXS_CHART
    value: "true"
  - name: ENABLE_TXS_STATS
    value: "true"
  - name: HIDE_BLOCK_MINER
    value: "true"
  - name: DISABLE_READ_API
    value: "true"
  - name: DISABLE_WRITE_API
    value: "true"
  - name: ECTO_USE_SSL
    value: "false"
  - name: SUPPORTED_CHAINS
    value: '[{"title":"POA","url":"https://blockscout.com/poa/core"},{"title":"Sokol","url":"https://blockscout.com/poa/sokol","test_net?":true},{"title":"Gnosis Chain","url":"https://blockscout.com/xdai/mainnet"},{"title":"Ethereum Classic","url":"https://blockscout.com/etc/mainnet","other?":true},{"title":"RSK","url":"https://blockscout.com/rsk/mainnet","other?":true},{"title":"Solar Chain Testnet","url":"https://sctscan.starnet.ltd/","test_net?":true}]'
  - name: APPS_MENU
    value: "false"
  - name: EXTERNAL_APPS
    value: ''
  - name: PORT
    value: "4000"
  - name: POOL_SIZE
    value: "40"
  - name: POOL_SIZE_API
    value: "10"
  - name: ENABLE_RUST_VERIFICATION_SERVICE
    value: "false"
  - name: RUST_VERIFICATION_SERVICE_URL
    value: "http://127.0.0.1:8043/"
  - name: ACCOUNT_ENABLED
    value: "false"

envFrom:
  - secretRef:
      #DATABASE_URL="postgresql://root:123456@127.0.0.1:5432/blockscout"
      #SECRET_KEY_BASE="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      name: blockscout-secret

extraVolumeMounts: # 增加挂载扩展挂载目录
  - mountPath: /etc/localtime
    name: localtime
    readOnly: true

extraVolumes: # 增加扩展卷
  - name: localtime
    hostPath:
      path: /etc/localtime

smartContractVerifier:
  enabled: false
  image:
    repository: ghcr.io/blockscout/smart-contract-verifier
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.5.0"

  env:
    - name: SMART_CONTRACT_VERIFIER__SERVER__ADDR
      value: "0.0.0.0:8043"
    - name: SMART_CONTRACT_VERIFIER__SOLIDITY__ENABLED
      value: "true"
    - name: SMART_CONTRACT_VERIFIER__SOLIDITY__COMPILERS_DIR
      value: "/tmp/solidity-compilers"
    - name: SMART_CONTRACT_VERIFIER__SOLIDITY__REFRESH_VERSIONS_SCHEDULE
      value: "0 0 * * * * *"
    - name: SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL
      value: "https://solc-bin.ethereum.org/linux-amd64/list.json"
    - name: SMART_CONTRACT_VERIFIER__VYPER__ENABLED
      value: "true"
    - name: SMART_CONTRACT_VERIFIER__VYPER__COMPILERS_DIR
      value: "/tmp/vyper-compilers"
    - name: SMART_CONTRACT_VERIFIER__VYPER__FETCHER__LIST__LIST_URL
      value: "https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json"
    - name: SMART_CONTRACT_VERIFIER__VYPER__REFRESH_VERSIONS_SCHEDULE
      value: "0 0 * * * * *"
    - name: SMART_CONTRACT_VERIFIER__SOURCIFY__ENABLED
      value: "true"
    - name: SMART_CONTRACT_VERIFIER__SOURCIFY__API_URL
      value: "https://sourcify.dev/server/"
    - name: SMART_CONTRACT_VERIFIER__SOURCIFY__VERIFICATION_ATTEMPTS
      value: "3"
    - name: SMART_CONTRACT_VERIFIER__SOURCIFY__REQUEST_TIMEOUT
      value: "10"
    - name: SMART_CONTRACT_VERIFIER__METRICS__ENABLED
      value: "false"
    - name: SMART_CONTRACT_VERIFIER__JAEGER__ENABLED
      value: "false"

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
